dist: focal
#language: dart
#
#dart:
#  - stable
language: shell

cache:
  directories:
    - $HOME/.pub-cache

before_install:
  #- git clone https://github.com/flutter/flutter.git -b stable --depth 1
  #- git clone https://github.com/flutter/flutter.git -b dev --depth 1
  #- git clone https://github.com/flutter/flutter.git -b master --depth 1
  - git clone https://github.com/flutter/flutter.git -b master
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor
  - flutter upgrade
  - flutter precache
  - flutter config --enable-web
  - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g firebase-tools@9.23.0
  #- npm install -g firebase-tools

install:
  - flutter pub get

script:
  - flutter build web --release
  
before_deploy:
  - echo "Files in build/web:"
  - ls -R build/web
  - echo "Contents of index.html:"
  - head -n 20 build/web/index.html || echo "index.html missing!"
  - echo "Token length: ${#FIREBASE_TOKEN}"
  
deploy:
  provider: script
  #script: firebase deploy --project swe6733wc --token "$FIREBASE_TOKEN" # I have a string literal I can use if this doesn't work
  script: firebase deploy --project swe6733wc --token "$FIREBASE_TOKEN" --debug
  skip_cleanup: true
  on:
    branch: dev
