language: dart

dart:
  - stable

cache:
  directories:
    - $HOME/.pub-cache

before_install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor
  - flutter config --enable-web
  - npm install -g firebase-tools@10.12.1
  #- npm install -g firebase-tools

install:
  - flutter pub get

script:
  - flutter build web --release

deploy:
  provider: script
  script: firebase deploy --project swe6733wc --token "$FIREBASE_TOKEN" # I have a string literal I can use if this doesn't work
  skip_cleanup: true
  on:
    branch: dev
